LIKELION-Android-Bootcamp-4th/Todori

app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateStudyScreen.kt
>  🔒PR 명명 규칙
>
<br>
-  T04
<br>
- 전체적인 UI 디자인
- 날짜 선택 -> Row 형태로 가볍게 처리
- 유효성 검증 로직
- 제목 1 ~ 20
- 내용 1 ~ 60
<br>
<br>
- 
<br>
=> [UI/T04] 스터디 생성 페이지

app/src/main/java/com/mukmuk/todori/data/remote/goal/Goal.kt, app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt, app/src/main/java/com/mukmuk/todori/ui/component/TodoItemEditRow.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/CreateGoalScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/CardHeaderSection.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/GoalPeriodStatus.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/GoalProgressSection.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/GoalTodoList.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/SingleDatePickerBottomSheet.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/GoalCard.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/card/StudyCard.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/GoalDetailScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/TodoDetailScreen.kt, app/src/main/java/com/mukmuk/todori/util/calculateDDayValue.kt
>  🔒PR 명명 규칙
>
<br>
-  D02 - 목표 로드맵 상세 화면
-  T03 - 목표 수정 화면
<br>
- 목표 로드맵 상세 화면 제작
- TodoItemEditRow 내 dueDate 변수를 통한 목표 로드맵 내 마감 기한 처리
- CreateGoalScreen 이동 처리
- Progress 진행률 바 탭에 맞게 변경
<br>
<br>
- 목표 수정 후 생성을 하면 기존 데이터가 남는 문제가 발생 -> 추후 DB 연결 시 삭제할 내용이라 수정X
- 
<br>
=> [UI/D02] 목표 로드맵 상세 화면 UI 제작 & 목표 수정 화면 전환 처리

app/build.gradle.kts, app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeEvent.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeState.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/components/MainTodoItemEditRow.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/components/PomoModeTextBox.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/components/TimerTextFieldInput.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_setting/HomeSettingEvent.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_setting/HomeSettingScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_setting/HomeSettingState.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_setting/HomeSettingViewModel.kt
-  M01 - 누적 공부 시간, 뽀모도로 타이머 화면
-  M02 - 뽀모도로 설정 화면
<br>
- 전체 UI 구성
- 누적 공부 시간 스톱워치 제작 (시작, 정지)
- 뽀모도로 타이머 제작 (현재 상태, 리셋)
- 뽀모도로 설정 TextField, on/off 토글 제작
- Todo 시간 기록
<br>
<br>
<br>
=> [UI/M01, M02] 메인 화면 (타이머, 설정) UI 구현

app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeState.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
-  M01 메인화면
<br>
- 타이머 리셋 시 집중 모드로 텍스트 박스 변경되도록 수정
<br>
<br>
- 
<br>
=> [UI/M01] 리셋 버튼 버그 수정

app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt, app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginEvent.kt, app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginState.kt, app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
-  L01 로그인 및 회원가입 화면
<br>
- 로그인 화면, 구조 제작
<br>
<br>
- 
<br>
=> [UI/L01] 로그인 및 회원가입 화면 제작

gradle/libs.versions.toml
>  🔒PR 명명 규칙
>
<br>
-  x
<br>
- firebase bom을 통해 버전 관리를 할려고 했지만  toml + bom 조합에서 Android Studio/IntelliJ가 bom 매핑을 제대로 캐싱하지 못하는 경우가 있다고 하네요 .. 어지럽습니당... 
- firebase 같은 경우 뭔가 계속해서 이런 버전이 안되거나 이런 문제가 많을 것으로 예상됩니다.
<br>
<br>
- 
<br>
=> [fix/firebase_setting] firebase error 수정

app/src/main/java/com/mukmuk/todori/data/repository/StudyRepository.kt, app/src/main/java/com/mukmuk/todori/data/service/StudyService.kt, app/src/main/java/com/mukmuk/todori/di/AppModule.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/CreateStudyScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/StudyViewModel.kt
>  🔒PR 명명 규칙
>
<br>
-  T01 - Todo 화면
<br>
- firebase 내 스터디 생성하도록 처리 완료
<br>
<br>
```kotlin
viewModelScope.launch(Dispatchers.IO) {
// leaderId -> 내 UID (로그인 처리 후 변경), leaderNickname -> 내 닉네임 (로그인 처리 후 변경) -> viewModel에서 처리
// val user = FirebaseAuth.getInstance().currentUser
// val leaderId = user?.uid ?: throw Exception("로그인 필요")
val leaderId = "testuser"
val leaderNickname = "edittest"
..... 
}
```
- 현재는 testuser가 들어가게끔 처리. 로그인 로직 처리 후 내 UID 로 하게끔 변경 예정
<br>
=> [feature/TODO-007] 스터디 생성 통신 완료

app/src/main/java/com/mukmuk/todori/data/repository/UserRepository.kt, app/src/main/java/com/mukmuk/todori/data/service/UserService.kt, app/src/main/java/com/mukmuk/todori/di/AppModule.kt, app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileManagementScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileViewModel.kt
<br>
- U01 마이페이지
- U04 프로필 관리
<br>
- 프로필 관리(U04) 화면에서 수정하면 마이페이지(U01)화면 프로필 조회(MYP-001)에 반영되고 서버에도 저장
<br>
<br>
- 커밋 제목을 안바꿨습니다 하하..
- 기능 ID 도 틀렸습니다.. (branch/commit) USER-001
<br>
=> [Feat/USER-001] 프로필 수정 기능

app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailItem.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/create/CreateCommunityScreen.kt, gradle/libs.versions.toml
+ agp 8.10.0 고정
>  🔒PR 명명 규칙
>
<br>
-  
<br>
- 커뮤니티 AppTextStyle 변경으로 인한 스타일 변경
<br>
<br>
- 
<br>
=> [fix/community] 커뮤니티 AppTextStyle 변경으로 인한 스타일 변경

app/src/main/java/com/mukmuk/todori/data/remote/goal/Goal.kt, app/src/main/java/com/mukmuk/todori/data/repository/UserRepository.kt, app/src/main/java/com/mukmuk/todori/data/service/UserService.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/DayStatsCard.kt
>  🔒PR 명명 규칙
>
<br>
-  U01, U03
<br>
- 마이페이지 내 완료한 목표 리스트 연동
<br>
<br>
- uid testuser으로 고정
<br>
=> [Feature/MYP-003] 완료한 목표 리스트 연동

app/src/main/java/com/mukmuk/todori/data/repository/DailyRecordRepository.kt, app/src/main/java/com/mukmuk/todori/data/service/DailyRecordService.kt, app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/MonthCard.kt, app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekCard.kt, app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/WeekGraph.kt, app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekState.kt, app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekTab.kt, app/src/main/java/com/mukmuk/todori/ui/screen/stats/tab/week/WeekViewModel.kt
>  🔒PR 명명 규칙
>
<br>
-  S01 통계화면
<br>
- week 탭 연동
<br>
<br>
- 
<br>
=> [Feature/STATS-005] Week tab 연동

app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileManagementScreen.kt
>  🔒PR 명명 규칙
>
<br>
-  U01
<br>
- testuser > uid 변경
<br>
<br>
- 
<br>
=> [Fix/MYP] 프로필 연결 uid로 변경

app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeState.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
-  M01 메인 화면
<br>
- 현재 로그인 한 계정 uid 연결
<br>
<br>
- 
<br>
=> [Feat/TMR-001] 현재 로그인 한 계정 uid 연결

app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt
-  M01 메인화면
<br>
- 화면 안 보일 경우 ui 그리지 않도록 수정
- 탭으로 화면 전환 시 타이머 멈춤 현상 수정
<br>
<br>
- 
<br>
=> [Fix/TMR-001] 수정

app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsViewModel.kt
>  🔒PR 명명 규칙
>
<br>
-  마이페이지 -> 완료한 목표
<br>
-  끝난 목표 testuser -> uid 변경
<br>
<br>
- 
<br>
=> [fix/completedGoal] 끝난 목표 testuser -> uid 변경

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/mukmuk/todori/data/repository/HomeRepository.kt, app/src/main/java/com/mukmuk/todori/data/service/HomeService.kt, app/src/main/java/com/mukmuk/todori/di/AppModule.kt, app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/components/TimerTextFieldInput2.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrState.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrViewModel.kt, gradle/libs.versions.toml
-  M01 메인화면
<br>
- 직접 시간 입력 기능 추가
- 추가 화면 UI
- FireStore, DataStore 연동
<br>
<br>
- 
<br>
=> [Feature/TMR-005] 타이머 직접 시간 입력

app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrState.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrViewModel.kt
-  M03 타이머 추가
<br>
- OCR 삭제
<br>
<br>
- 
<br>
=> [Fix/TMR-005] OCR 삭제

app/src/main/java/com/mukmuk/todori/widget/timer/TimerWidget.kt, app/src/main/java/com/mukmuk/todori/widget/totaltime/TotalTimeWidget.kt
-  M01 메인 화면
<br>
- 위젯 배경 추가
<br>
<br>
- 
<br>
=> [Fix/WGT-0012] 위젯 배경 추가

app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_ocr/HomeOcrViewModel.kt, app/src/main/java/com/mukmuk/todori/widget/timer/TimerService.kt
-  
<br>
- 타이머 추가 시 홈 화면 바로 업데이트
- 타이머 버그 수정
<br>
<br>
- 
<br>
=> [Fix/TMR-005] 타이머 추가 시 홈 화면 바로 업데이트

app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailViewModel.kt
>  🔒PR 명명 규칙
>
<br>
-  W03
<br>
- 카테고리 삭제 시 위젯 업데이트 추가
<br>
<br>
- 
<br>
>
=> [Fix/widget 001] 카테고리 삭제 시 위젯 업데이트

app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/goal/GoalDetailScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/todo/TodoDetailScreen.kt
>  🔒PR 명명 규칙
>
<br>
-  T01
<br>
- 개인 TODO 화면 스크롤 추가
- 목표 로드맵 화면 스크롤 추가
<br>
<br>
- 
<br>
>
=> [fix/T01] TODO 화면 스크롤 추가

app/src/main/java/com/mukmuk/todori/ui/screen/stats/component/day/CalendarCard.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/WeekCalendar.kt
>  🔒PR 명명 규칙
>
<br>
-  T01
<br>
- 달력 공부시간 기준 통일 
- CalendarCard 기준으로 설정 (~2시간 / 2~6시간 / 6시간~) 
<br>
<br>
- 
<br>
>
=> [fix/T01_2] 달력 공부시간 기준 통일

app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt
-  U01 마이페이지
<br>
- 탈퇴, 로그아웃 시 Toast 메시지
- 로그아웃 시 다이얼로그
<br>
<br>
- 
<br>
=> [Feat/LOGIN-003] 로그아웃 시 다이얼로그

app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityListData.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/components/StudyDetailCard.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyCard.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyMetaInfoRow.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/StudyTodoInputCard.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/list/study/StudyTodoList.kt, app/src/main/java/com/mukmuk/todori/util/DateUtil.kt
-  T01, D03
<br>
- 스터디 해당 요일에만 보이도록 수정
- 날짜 별로 디데이 변경
- Todo 완료 시 리스트 아래로 이동
<br>
<br>
- 
<br>
=> [Fix/STUDY-001] 스터디 이슈관리

app/src/main/java/com/mukmuk/todori/ui/screen/splash/SplashScreen.kt
>  🔒PR 명명 규칙
>
<br>
-  splash
<br>
- splash 화면에서 기존에 이미지 색상이 혼자 붕뜨는 문제 해결
<br>
<br>
- 순식간에 사라져서 캡쳐 못했어요. 집중해서 봐야합니다.
<br>
=> [fix/splash] 사진 크기 조절 + 텍스트

app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/DateRangePickerBottomSheet.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/create/CreateGoalScreen.kt
-  T03
<br>
- 날짜 재선택 수정
- 수정 시 원래 기간 설정
- 생성 시 오늘 날짜 시작일 지정
- 기간 선택하지 않고 완료 버튼 클릭 시 Toast
<br>
<br>
- 
<br>
=> [Fix/TODO-008] 목표 생성 / 수정 기간 이슈관리

app/src/main/java/com/mukmuk/todori/data/local/datastore/AuthLocalRepository.kt, app/src/main/java/com/mukmuk/todori/data/local/datastore/DataStoreModule.kt, app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/login/LoginViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/login/components/RecentLoginBox.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileViewModel.kt
-  L01
<br>
- DataStore 로그인 정보 저장
- 버튼에 최근 로그인 표시
<br>
<br>
- 
<br>
=> [Feat/LOGIN-003] 최근 로그인 표시

app/src/main/java/com/mukmuk/todori/data/local/datastore/HomeSettingRepository.kt, app/src/main/java/com/mukmuk/todori/data/local/datastore/RecordSettingRepository.kt, app/src/main/java/com/mukmuk/todori/data/local/datastore/TodayTodoRepository.kt, app/src/main/java/com/mukmuk/todori/data/repository/HomeRepository.kt, app/src/main/java/com/mukmuk/todori/data/repository/TodoRepository.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailComment.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailCommentReply.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityListOption.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunitySearchData.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/ProfileViewModel.kt
-  M01
<br>
- HomeViewModel Observe 로직 개선
- 로그아웃 시 DataStore 초기화
- 로그아웃 시 타이머 상태 초기화
- FireStore Flow 변경
<br>
<br>
- 
<br>
=> [Fix/TMR-001] 홈 화면 Todo 이슈 관리

app/src/main/java/com/mukmuk/todori/ui/screen/todo/TodoScreen.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
- Todo 탭 이름 개인 -> Todo 변경
<br>
<br>
- 
<br>
=> [fix/todo_name] 개인 -> TODO 로 변경

app/src/main/java/com/mukmuk/todori/navigation/AppNavigation.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt, app/src/main/java/com/mukmuk/todori/widget/LaunchActivityCallback.kt, app/src/main/java/com/mukmuk/todori/widget/TodoLaunchActivityCallback.kt, app/src/main/java/com/mukmuk/todori/widget/goaldaycount/DayCountWidget.kt, app/src/main/java/com/mukmuk/todori/widget/timer/TimerService.kt, app/src/main/java/com/mukmuk/todori/widget/timer/TimerWidget.kt, app/src/main/java/com/mukmuk/todori/widget/todos/TodoWidget.kt, app/src/main/java/com/mukmuk/todori/widget/totaltime/TotalTimeWidget.kt
-  
<br>
- 로그인 정보 없을 시 로그인 화면 이동
<br>
<br>
- 
<br>
=> [Fix/Widget-001] Todo 위젯 이슈관리

app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/CompletedGoalsViewModel.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
-  완료한 목표 텍스트 옆 size 삭제 및 통신 시isLoading Indicator 추가
<br>
<br>
- 
<br>
=> [fix/completeGoal] 완료 목표 텍스트 옆 size 삭제 및 통신 시isLoading Indicator 추가

app/src/main/java/com/mukmuk/todori/ui/screen/mypage/MyPageScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/mypage/component/ProfileSection.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
- 프로필 사진 배경 처리
- 네트워크 통신 시 CircleIndicator 사용
<br>
<br>
- 
<br>
=> [Fix/profile] 프로필 사진 & indicator

app/src/main/java/com/mukmuk/todori/ui/screen/todo/component/SingleDatePickerBottomSheet.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/goal/GoalDetailScreen.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
<br>
<br>
- 
<br>
=> [Fix/Goal_Detail] 목표 로드맵 날짜 선택 바텀시트 캘린더 월 변경 처리 & loading indicator & badge 배경색 처리

app/src/main/java/com/mukmuk/todori/data/service/AuthService.kt, app/src/main/java/com/mukmuk/todori/data/service/MyFirebaseMessagingService.kt
>  🔒PR 명명 규칙
>
<br>
-  x
<br>
- 로그아웃 시 FCM 토큰을 삭제해서 로그아웃상태나/ 재로그인시 이전아이디기준 알림이 가지 않게 수정
<br>
<br>
- 
<br>
=> [FIX/FCM-001] 로그아웃시 알림 토큰 삭제

functions/index.js, functions/notify.js, functions/quests.js
-index 파일에 함수들 추가
>  🔒PR 명명 규칙
>
<br>
-  
<br>
- quest.js 파일/ notify.js 파일 업로드
- index.js 파일에 퀘스트/알림 함수 추가
<br>
<br>
- 
<br>
=> [feature] quest/ fcm js 파일 업로드

app/src/main/java/com/mukmuk/todori/ui/screen/home/HomeViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/home/home_setting/HomeSettingScreen.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
<br>
<br>
- 
<br>
=> [Feat/timer] TimerSetting TextInput -> Slider & dailyRecord 업데이트 로직

app/src/main/java/com/mukmuk/todori/data/remote/community/StudyPost.kt, app/src/main/java/com/mukmuk/todori/data/remote/community/StudyPostComment.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/CommentUiModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/PostUiModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityDetailComment.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailState.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailViewModel.kt
-  
<br>
- 드롭다운에 전체 대분류 추가
- 닉네임 변경 시 댓글 업데이트
<br>
<br>
- 
<br>
=> [Fix/COM-00] 커뮤니티 이슈 관리

functions/quests.js
>  🔒PR 명명 규칙
>
<br>
-  
<br>
- 회고 v2로 변경 퀘스트 조건
<br>
<br>
- 
<br>
=> [FIX/quest] quest 회고 조건 변경

app/src/main/java/com/mukmuk/todori/data/repository/CommunityRepository.kt, app/src/main/java/com/mukmuk/todori/data/repository/GoalTodoRepository.kt, app/src/main/java/com/mukmuk/todori/data/service/CommunityService.kt, app/src/main/java/com/mukmuk/todori/data/service/GoalTodoService.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailViewModel.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/goal/GoalDetailScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/goal/GoalDetailViewModel.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
<br>
<br>
- 
<br>
=> [Fix/refresh] 목표 Todo 생성 , 수정 ,삭제 시 전체 reload 해결

app/src/main/java/com/mukmuk/todori/ui/screen/splash/SplashScreen.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
<br>
<br>
- 
<br>
=> [refactor/splash] splash 2초 딜레이 설정

app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityPost.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt
-  
<br>
- surface 사용
<br>
<br>
- 
<br>
=> [Fix/COM-001] 태그 글자 잘림 수정

app/src/main/java/com/mukmuk/todori/ui/screen/community/CommunityScreen.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunityPost.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailScreen.kt
-  
<br>
- 참여하기 버튼 클릭 시 스낵바 이동하기 클릭으로 스터디 상세 이동
<br>
<br>
- 
<br>
=> [Fix/COM-001] 참여하기 버튼 클릭 시 스낵바

app/src/main/java/com/mukmuk/todori/ui/screen/todo/detail/study/StudyDetailScreen.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
<br>
<br>
- 
<br>
=> [fix/keyboard] 키보드 오류 해결

app/src/main/java/com/mukmuk/todori/ui/screen/community/components/CommunitySearchData.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
- 최근 검색어 박스 수정
<br>
<br>
- 
<br>
> <img width="399" height="167" alt="image" src="https://github.com/user-attachments/assets/d89b28dd-b42a-4424-92f3-8260e0886b94" />
=> [FIX/c02] 최근 검색어 박스 수정

app/src/main/java/com/mukmuk/todori/data/repository/CommunityRepository.kt, app/src/main/java/com/mukmuk/todori/data/service/CommunityService.kt, app/src/main/java/com/mukmuk/todori/ui/screen/community/detail/CommunityDetailViewModel.kt
>  🔒PR 명명 규칙
>
<br>
-  
<br>
<br>
<br>
- 
<br>
=> [fix/community] 커뮤니티 멤버 추가 오류 해결
